language: csharp
mono: none
dotnet: 2.1.105
script:
  - dotnet build WorkoutTracker.sln
  - dotnet test WorkoutTracker.Domain.UnitTests/WorkoutTracker.Domain.UnitTests.csproj --no-build
  - echo 'done!'